/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "print_hex.h"


void
hex_p_1(char *host,char *data) 
{
	CLIENT *clnt;
	void  *result_1;
	input  hex_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, HEX_P, HEX_V, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = hex_1(&hex_1_arg, clnt);
	*hex_1_arg.data = *data;
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host data\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	hex_p_1 (host,argv[2]);
exit (0);
}
